### ISSUE TITLE
AttributeError: 'BertConfig' object has no attribute 'reduce_dim'

### ISSUE THREAD

**Issue by BarryZM** [Lisennlp/two_sentences_classifier#1]
请问是对pytorch版本有要求么？

**Comment by Lisennlp** [comment]
> 请问是对pytorch版本有要求么？

不要超过1.5，不过尽量使用torch==1.0.1.post2。你这个问题已经修复了，是在two_sentences_classifier.sh中使用的训练py文件不对。已更正，谢谢指出。

**Comment by Lisennlp** [comment]
bug is repaired
